Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pudb/__init__.py", line 77, in runscript
    dbg._runscript(mainpyfile)
  File "/Library/Python/2.7/site-packages/pudb/debugger.py", line 418, in _runscript
    self.run(statement, globals=globals_, locals=locals_)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "muxi.py", line 11, in <module>
    """
  File "muxi.py", line 11, in <module>
    """
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Library/Python/2.7/site-packages/pudb/debugger.py", line 173, in dispatch_line
    self.user_line(frame)
  File "/Library/Python/2.7/site-packages/pudb/debugger.py", line 370, in user_line
    self.interaction(frame)
  File "/Library/Python/2.7/site-packages/pudb/debugger.py", line 338, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/Library/Python/2.7/site-packages/pudb/debugger.py", line 2020, in call_with_ui
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pudb/debugger.py", line 2225, in interaction
    self.event_loop()
  File "/Library/Python/2.7/site-packages/pudb/debugger.py", line 2191, in event_loop
    toplevel.keypress(self.size, k)
  File "/Library/Python/2.7/site-packages/pudb/ui_tools.py", line 83, in keypress
    result = self._w.keypress(size, key)
  File "/Library/Python/2.7/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/Library/Python/2.7/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/Library/Python/2.7/site-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/Library/Python/2.7/site-packages/pudb/ui_tools.py", line 88, in keypress
    return handler(self, size, key)
  File "/Library/Python/2.7/site-packages/pudb/debugger.py", line 1081, in step
    end()
  File "/Library/Python/2.7/site-packages/pudb/debugger.py", line 1066, in end
    self.debugger.save_breakpoints()
  File "/Library/Python/2.7/site-packages/pudb/debugger.py", line 237, in save_breakpoints
    if not bp.temporary])
  File "/Library/Python/2.7/site-packages/pudb/settings.py", line 480, in save_breakpoints
    histfile = open(get_breakpoints_file_name(), 'w')
IOError: [Errno 13] Permission denied: '/Users/apple/.config/pudb/saved-breakpoints-2.7'
